name: Build RSS Feed

on:
  push:
    branches:
      - dev
    paths-ignore:
      - rss.xml

jobs:
  build-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run RSS generator
        run: python ./rss-generator.py
      
      - name: Log RSS validation output
        run: |
            curl -s -F "url=https://raw.githubusercontent.com/charliefox84/iryna-watch/dev/rss.xml" https://validator.w3.org/feed/check.cgi > ./rss-validator.log  

      - name: Push changes
        if: github.ref == 'refs/heads/dev'
        env:
          GH_PAT: ${{ secrets.RSS_GH_PAT }}
        run: |
          git config user.name "CharlieFox84"
          git config user.email "235750736+CharlieFox84@users.noreply.github.com"  # optional, but match your GitHub identity
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git fetch origin
          git diff --quiet rss.xml || (
            git add rss.xml
            git commit -m "chore: auto-build rss.xml"
            git push origin HEAD:dev
          )
